trigger:
- none
# - development

variables:
  system.debug: true
  isMasterBranch: $[eq(variables['Build.SourceBranchName'], 'master')]

stages:
- stage: amd64
  displayName: amd64 (Intel/AMD)
  dependsOn: []
  jobs:
  - template: .azure-pipelines-job.yml
    parameters:
      arch: amd64
      username: $(DOCKER_USERNAME)
      password: $(DOCKER_PASSWORD)

- stage: arm32v6
  displayName: arm32v6 (Pi 1+, Zero and other armhf)
  dependsOn:
    - amd64
  jobs:
  - template: .azure-pipelines-job.yml
    parameters:
      arch: arm32v6
      username: $(DOCKER_USERNAME)
      password: $(DOCKER_PASSWORD)

- stage: arm32v7
  displayName: arm32v7 (Pi 1+ and other armhf)
  dependsOn:
    - amd64
  jobs:
  - template: .azure-pipelines-job.yml
    parameters:
      arch: arm32v7
      username: $(DOCKER_USERNAME)
      password: $(DOCKER_PASSWORD)

- stage: arm64v8
  displayName: arm64v8 (Pi 3+ and other ARM64)
  dependsOn:
    - amd64
  jobs:
  - template: .azure-pipelines-job.yml
    parameters:
      arch: arm64v8
      username: $(DOCKER_USERNAME)
      password: $(DOCKER_PASSWORD)

- stage: Manifest
  displayName: multi-arch manifest
  condition: and(succeeded(), eq(variables.isMasterBranch, true))
  dependsOn:
    - amd64
    - arm32v6
    - arm32v7
    - arm64v8
  variables:
    - name: DOCKER
      value: docker --config=/home/vsts/.docker
  jobs:
  - job: Manifest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - script: |
            echo $(DOCKER_PASSWORD) | $(DOCKER) login --username $(DOCKER_USERNAME) --password-stdin
            make manifest
