blank_issues_enabled: false
contact_links:
  - name: â” I have an issue related to DSMR Reader, not specifically DSMR Reader for Docker
    url: https://github.com/dsmrreader/dsmr-reader/issues
    about: If you are unsure where to go, then contacting the DSMR Reader developer(s) is recommended; Just ask!
